set trace on .
set trace select on .
trace select ----solveBubblesCond
             ----solveBubbles
             ----procModule1
             ----procModule2
             ----procModule3
             ----procModule4
             ----parseDecl
             evalPreModule
             evalPreModule1
             evalPreModule2
             ----procModule4
             ----solveBubblesMod
             ----solveBubblesModAux
             ----solveBubblesOps
             ----solveBubblesEq
             ----metaParse
             metaStratParse
             ----setStratDefs
             ----createCopy
             ----prepPar
             ----prepParImports
             ----setName
             ----applyMapsToModule
             ----maps2rens
             ----breakMb
             ----breakMbAux
             ----parseSort
             ----parseType
             ----evalViewExpression
             ----procView
             ----procView2
             ----viewInst
             ----prepViewExpression
             ----evalModExp
             ----viewInst
             ----viewInstAux
             ----insertView
             ----maps2rens
             ----genMapsSorts
             ----setSortMappings
             ----setOpMappings
             ----applyMapsToMaps
             .
set print conceal on .
print conceal mod_is_sorts_.____endfm
              mod_is_sorts_._____endm
              db
              .
eof

normalize
createCopy
prepParImports
